"""Type declarations for the PyO3 ``brass_ai._engine`` extension.

Rust implementation: ``../../engine/src/bridge/pymod.rs`` (`PyGame` and its
``#[pymethods]`` block). Ctrl+click the relative path in IDEs that recognize
paths in comments; otherwise use it as the manual navigation target.
"""

from typing import Any, Callable, List, Optional, Sequence, Tuple, Union

import numpy as np
from numpy.typing import NDArray

ACTION_FEATURE_DIM: int
ACTION_FEATURE_SCHEMA_VERSION: int
BOARD_PLANES: int
BOARD_CELLS: int
LINK_PLANES: int
LINK_CELLS: int
GLOBAL_LEN: int
HAND_LEN: int
MAX_PLAYERS: int
STATE_FEATURE_SCHEMA_VERSION: int
LOCATION_COUNT: int
BOARD_CELL_LOCATIONS: List[int]
CONNECTION_ENDPOINTS: List[int]
CONNECTION_VIA_FARMS: List[int]

NetCallback = Callable[
    [Any, Any, Any, Any, Any, Any, Any],
    Tuple[NDArray[np.float32], NDArray[np.float32]],
]


# Rust implementation: ../../engine/src/bridge/pymod.rs (`PyGame`).
class GameState:
    def __init__(self, seed: int, players: int) -> None: ...

    @property
    def current_player_id(self) -> int: ...
    @property
    def player_count(self) -> int: ...
    @property
    def era(self) -> int: ...
    @property
    def round(self) -> int: ...
    @property
    def turn_order(self) -> List[int]: ...
    @property
    def game_over(self) -> bool: ...
    @property
    def current_player_money(self) -> int: ...

    def clone(self) -> "GameState": ...
    def snapshot(self) -> bytes: ...
    @staticmethod
    def from_snapshot(snapshot: Union[bytes, bytearray, Sequence[int]]) -> "GameState": ...

    def legal_moves(self) -> List[Tuple[int, str, str]]: ...
    def legal_operations(self) -> List[Tuple[int, str, int, List[Tuple[int, float]]]]: ...
    def resolve_legal_operation(self, operation_id: int, selected_cards: List[int]) -> str: ...
    def legal_candidates(self) -> List[Tuple[str, List[float]]]: ...
    def heuristic_candidates(
        self,
    ) -> Tuple[List[float], List[float], List[float], str, int, float, float, int]: ...
    def search_net(
        self,
        net_fn: NetCallback,
        sims: int,
        c_puct: float,
        max_depth: int,
        dirichlet_alpha: float,
        dirichlet_weight: float,
        add_root_noise: bool,
        batch_size: int = 64,
        candidate_k: int = 0,
    ) -> Tuple[Optional[str], List[Tuple[int, str, int]], List[int]]: ...

    def apply_move(self, canonical: str) -> str: ...
    def apply_move_raw(self, canonical: str) -> Tuple[str, bool]: ...
    def advance_turn_raw(self) -> str: ...
    def finish_canal_era(self) -> None: ...
    def finish_game(self) -> None: ...

    def replay_header(self) -> str: ...
    def replay_move_detail(self, canonical: str) -> str: ...
    def replay_action_type(self, canonical: str) -> Tuple[str, int]: ...
    def replay_era_score(self, pid: int) -> str: ...
    def replay_tiles(self, pid: int, flipped_only: bool = False) -> str: ...
    def replay_cleanup(self) -> str: ...
    def replay_player_state(self, pid: int) -> str: ...
    def replay_board(self) -> str: ...
    def replay_merchants(self) -> str: ...
    def replay_hand(self, pid: int) -> str: ...
    def replay_stats_line(
        self,
        build: Sequence[int],
        network: int,
        dbl_rail: int,
        develop: int,
        sell: int,
        loan: int,
        pass_: int,
        scout: int,
    ) -> str: ...

    def final_econ(self) -> List[Tuple[int, int]]: ...
    def canal_econ(self) -> List[Tuple[int, int]]: ...
    def determinize(self) -> "GameState": ...
    def state_to_tensor(
        self, perspective: Optional[int] = None
    ) -> Tuple[
        NDArray[np.float32],
        NDArray[np.float32],
        NDArray[np.float32],
        NDArray[np.float32],
        NDArray[np.float32],
    ]: ...
    def player_vps(self) -> List[int]: ...
    def final_ranking(self) -> List[int]: ...
    def choose_heuristic(self) -> Tuple[str, str, float]: ...
